# This file is auto-generated by the `evennia connections` wizard.
# Don't edit manually, your changes will be overwritten.

GAME_INDEX_ENABLED = True
GAME_INDEX_LISTING = \
{   'game_name': 'Aether Lost',
    'game_status': 'pre-alpha',
    'game_website': '',
    'listing_contact': 'cmdrapollobusiness@gmail.com',
    'long_description': 'A MUX about cowboy robots on mars hunting dinosaurs. '
                        'This game is currently in active development and is '
                        'not public. I plan on releasing it around Christmas '
                        'time, though development will hopefully still '
                        "continue after then. For now, I'm just slowly working "
                        'on learning Evennia and building content.',
    'short_description': 'A MUX about cowboy robots on mars hunting dinosaurs. '
                         "What's not to love?",
    'telnet_hostname': '',
    'telnet_port': '',
    'web_client_url': ''}